python selftraining.py \
    --src-dataset dukemtmc \
    --tgt-dataset market1501 \
    --height 256 \
    --width 128 \
    --resume ./pretrained_models/dukemtmc_trained.pth.tar \
    --print-freq 20 \
    --iteration 20 \
    --logs-dir ./logs/duke2market/ \
    --gpu-devices 2,3 \
